name: Sample Action
on:
  workflow_dispatch:
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check version of Git
        run: git -v
        continue-on-error: true
      - name: Try pulling private repository
        run: git clone https://oauth:${{ secrets.PAT }}@github.com/OverDriveInc/AppScorecard.git
        continue-on-error: true
      - name: Running `ls` command to verify cloning
        run: ls -a
        continue-on-error: true
      - name: See if jq is installed
        run: jq
        continue-on-error: true
      - name: Use jq to echo the repo names
        run: |
            curl -X POST https://api.github.com/graphql -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.PAT }}" -d '\
            {\
              "query": "query($org: String!, $teamSlug: String!) { organization(login: $org) { team(slug: $teamSlug) { repositories(first: 100) { totalCount nodes { name url } } } } }",\
              "variables":\
                "org": "OverDriveInc",\
                "teamSlug": "tools-qa"\
              }\
            }'
        # jq '.[] | .name' AppScorecard/repos.json
        continue-on-error: true
