name: Sample Action
on:
  workflow_dispatch:
  pull_request:
env:
  GH_TOKEN: ${{ secrets.PAT }}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check version of Git
        run: git -v
        continue-on-error: true
      # - name: Try pulling private repository
      #   run: git clone https://oauth:${{ secrets.PAT }}@github.com/OverDriveInc/AppScorecard.git
      #   continue-on-error: true
      - name: Setup Git email
        run: git config --global user.email ""
      - name: Setup Git username
        run: git config --global user.name "GitHub Actions"
      - name: Running `ls` command to verify cloning
        run: ls -a
      - name: See if jq is installed
        run: jq
      - name: Use jq to echo the repo names
        run: |
          curl -X POST https://api.github.com/graphql \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -d '{
              "query": "query($org: String!, $teamSlug: String!) { organization(login: $org) { team(slug: $teamSlug) { repositories(first: 100) { totalCount nodes { name url } } } } }",
              "variables": {
                "org": "OverDriveInc",
                "teamSlug": "tools-qa"
              }
            }' | jq -r '.data.organization.team.repositories.nodes | .[] | .name' | grep -ie AppScorecard > repo_names.txt
      - name: Clone each repository, create .gitattributes file, and run git add --renormalize
        run: |
          while IFS= read -r repo; do
            git clone https://oauth2:${{ secrets.PAT }}@github.com/OverDriveInc/$repo
            cd $repo
            echo "* text=auto" > .gitattributes
            git add --renormalize .
            if [ -n "$(git status --porcelain)" ]; then
              git checkout -b add-gitattributes
              git add -A
              git commit -m "Add .gitattributes file and renormalize"
              git push https://oauth2:${{ secrets.PAT }}@github.com/OverDriveInc/$repo add-gitattributes -f
              if ! gh pr list --repo OverDriveInc/$repo --head add-gitattributes --state open --json number --jq '.[0]'; then
                gh pr create --title "Add .gitattributes file and renormalize" --body "This PR adds a .gitattributes file and renormalizes the repository." --head add-gitattributes --repo OverDriveInc/$repo
              fi
            fi
            cd ..
          done < repo_names.txt
      - name: See result of gh pr list
        run: gh pr list --repo OverDriveInc/AppScorecard --head add-gitattributes --state open --json number --jq '.[0]'
