name: Sample Action
on:
  workflow_dispatch:
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check version of Git
        run: git -v
        continue-on-error: true
